### ISSUE TITLE
Alternative medication against arrays

### ISSUE THREAD

**Issue by szepeviktor** [hypnotox/abyss#4]
_Let's take a handful of pills and look into the mirror!_

💊💊💊💊💊

- https://github.com/zakirullin/mess - there is no schema, the user reads whatever he wants from the _messy_ array
- https://github.com/rapidwebltd/array_undot - builds an array from dot notation
- https://github.com/justinrainbow/json-schema - a JSON schema validator, let's see how they do it!
- **our ancient nemesis** - https://github.com/ilsenem/matcher

**Comment by szepeviktor** [comment]
I think we should support custom types, not just built-in PHP types. 🎇 This is almost array -> object conversion!

So my unstoppable brain wants to go further: what will our users do with these _tamed_ arrays?
```php
$productBuilder = new Aybss\ObjectBuilder($schema, App\Models\Product::class);
$myProduct = $productBuilder->make($arrayFromOuterSpaceApi); // throws exceptions
```

**Comment by hypnotox** [comment]
I agree, it should support custom types 100%.
The structure also has to be able to define key type as well as value type. A possible feature would also be key or value constraints, though I'm not sure if that would still be in scope for this library.

It looks like the most similar to this would be JSON schema in what the validation allows.
Matcher's approach is limited, from what i can see, in the ability to define key types or more intricate value validation.

The target feature set is currently not set in stone and we don't have to include everything possible.

**Comment by szepeviktor** [comment]
You have to know that I'm against non-list type arrays.

> An array is a dumb container of unknown data.

_from https://gist.github.com/szepeviktor/9b70cab1b3313ff35e0ac1ace2d63e62_

So a "valid" array should not be the end of the journey.

**Comment by hypnotox** [comment]
I get where you're coming from, but users of the library will have cases where they have to validate keys as well, especially if you want to introduce schema validation after the fact to ensure behaviour doesn't change.

The library should force the user to use it in the way we intend, but we cannot force what their schema might look like, since this would narrow the usability.

**Comment by szepeviktor** [comment]
> they have to validate keys as well,

All right.

Feed your brain!
- https://github.com/CuyZ/Valinor
- https://github.com/EventSaucePHP/ObjectHydrator
- https://github.com/spatie/data-transfer-object
- https://github.com/janephp/janephp/tree/next/src/Component/AutoMapper
