### ISSUE TITLE
Structure rework

### ISSUE THREAD

**Issue by hypnotox** [hypnotox/abyss#5]
@szepeviktor I just pushed a [new branch](https://github.com/hypnotox/abyss/tree/rework) with an initial set of classes which should show the structure i have in mind right now.
It's still very early into the concept, but if you see any problems or have any ideas with it you can bring them up here.

**Comment by szepeviktor** [comment]
Could ValueType be an ARRAY? With tree-like arrays.

**Comment by hypnotox** [comment]
Yes, nesting is very much necessary :D

I just fixed some things, my IDE is a bit fucked up rn.
Developing on Windows with WSL2 is a pain sometimes, will probably switch to Linux again in the near future.

Will continue on that branch this weekend, i hope that i can get the basic structure down in that time frame.
