### ISSUE TITLE
Pure lists

### ISSUE THREAD

**Issue by szepeviktor** [hypnotox/abyss#6]
Please consider adding a check for lists, arrays with the same element type with zero-based increasing integer keys.

```php
[
    'apple',
    'pear',
    'pineapple',
]

[
    0 => 'apple',
    1 => 'pear',
    2 => 'pineapple',
]
```

**Comment by hypnotox** [comment]
In which cases do you mean? For all of the arrays that are being used internally or in the constructor?

**Comment by szepeviktor** [comment]
I mean this would be a verification feature in the schema.

**Comment by hypnotox** [comment]
Oh yes, sure 👍🏻 
I'll probably not do that (actually checking for it to be a list) for internal behaviour, Psalm on level 1 should be enough.

I'll write a list of all the types / validators and features I'm thinking off today or tomorrow and will update the readme.
